name: Bug report
description: Let us know about functionality that is not working as expected
title: "Bug report: <short description>"
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting the issue you are facing.
        
        Please complete the below form to ensure we have the necessary details to assist you.
  - type: input
    id: description
    attributes:
      label: Description
      description: |
        Provide a short description of the issue you are facing
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide the steps you have taken so that we can reproduce the error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected results
      description: Provide a description of what you expect to happen
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual results
      description: Provide a description of what actually happens
    validations:
      required: true
