name: New Command
description: Create a specification for a new command to add to the CLI
title: "New command: <short description>"
labels: [new feature]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new command to be added to this project.
        
        Please complete the below template to ensure we have the necessary details to assist you.
  - type: input
    id: usage
    attributes:
      label: Usage
      description: |
        This should describe how the command will be used.
        
        Commands should follow a pattern of `service` `entity` `verb`. 
        
        Approved verbs include `get`, `set`, `remove`, `add`, `list`.
      placeholder: e.g. m365 spo web get [options]
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Description
      description: |
        Provide a short description of what the command does
      placeholder: e.g. Retrieve information about the specified site
    validations:
      required: true
  - type: textarea
    id: options
    attributes:
      label: Options
      description: |
        Amend and complete the table below with the options used on this command.
        
        A short (single character) and long version of the option should be provided along with `[optional]` or `<required>` parameters.
      value: |
        Option | Description
        -- | --
        `-i, --teamId <teamId>` | The Id of the Microsoft Team
        `-r, --role [role]` | Filter the results to only users with the given role: `Owner` or `Member`.
      render: md
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: Additional Info
      description: |
        Provide additional information or links to resources that can help with the creation of this command.
    validations:
      required: false
