name: New Command
description: Create a specification for a new command to add to the CLI
title: "New command: <short description>"
labels: [new feature]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new command specification!
  - type: input
    id: usage
    attributes:
      label: Usage
      description: |
        How will this command be executed in the terminal?
        
        Commands should follow a pattern of `service` `entity` `verb`. 
        
        Approved verbs include `get`, `set`, `remove`, `add`, `list`.
      placeholder: e.g. m365 spo web get [options]
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Description
      description: |
        Provide a short description of what the command does?
      placeholder: e.g. Retrieve information about the specified site
    validations:
      required: true
