name: New Command
description: Create a specification for a new command to add to the CLI
title: "New command: <short description>"
labels: [new feature]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new command specification!
  - type: input
    id: usage
    attributes:
      label: Usage
      description: How will this command be executed? Commands should follow a pattern of service entity verb. Verbs include get, set, remove, add, list.
      placeholder: i.e. m365 spo web get [options]
    validations:
      required: true
