name: New Command
description: Create a specification for a new command to add to the CLI
title: "New command: <short description>"
labels: [new feature]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this new command specification!
  - type: input
    id: usage
    attributes:
      label: Usage
      description: |
        How will this command be executed in the terminal?
        
        Commands should follow a pattern of `service` `entity` `verb`. 
        
        Approved verbs include `get`, `set`, `remove`, `add`, `list`.
      placeholder: e.g. m365 spo web get [options]
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Description
      description: |
        Provide a short description of what the command does?
      placeholder: e.g. Retrieve information about the specified site
    validations:
      required: true
  - type: textarea
    id: options
    attributes:
      label: Options
      description: |
        Complete the table below with the options used on this command. 
        
        A short (single character) and long version of the option should be provided along with `[optional]` or `<required>` parameters.
      placeholder: |
        Option | Description  
        -- | --
        `-i, --teamId <teamId>` | The Id of the Microsoft Team
        `-r, --role [role]` | Filter the results to only users with the given role: `Owner` or `Member`.
    validations:
      required: true
